name: campus_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 4.5.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  device_info_plus: ^9.1.1
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.0.1
  hive: ^2.2.3
  intl: any
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  package_info_plus: ^5.0.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^24.1.41
  syncfusion_flutter_charts: ^24.1.41
  url_launcher: ^6.1.10
  video_player: ^2.6.1
  xml: ^6.2.2
  xml2json: ^6.1.0
  barcode_widget: ^2.0.4
  lottie: ^2.3.2
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  timeago: ^3.4.0
  grpc: ^3.2.4
  protobuf: ^3.0.0
  syncfusion_flutter_datepicker: ^24.1.41
  google_maps_flutter: ^2.4.0
  map_launcher: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  uuid: ^4.2.1
  collection: ^1.18.0
  firebase_crashlytics: ^3.4.6
  firebase_core: ^2.24.0
  flutter_linkify: ^6.0.0
  permission_handler: ^11.1.0

dependency_overrides:
  xml2json:
    git:
      url: https://github.com/jakobkoerber/xml2json.git
      ref: master
  grpc:
    git:
      url: https://github.com/jakobkoerber/grpc-dart.git
      ref: master
  google_maps_flutter_ios:
    git:
      url: https://github.com/jakobkoerber/packages.git
      path: packages/google_maps_flutter/google_maps_flutter_ios
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/mapStyles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/logos/tum-logo-rainbow.png
    - assets/images/placeholders/portrait_placeholder.png
    - assets/images/placeholders/movie_placeholder.png
    - assets/images/placeholders/news_placeholder.png
    - assets/images/errors/error.png
    - assets/images/errors/error_crop.png
    - assets/images/errors/error_square.png
    - assets/lottieFiles/gradient_background_blue_red.json
    - assets/lottieFiles/gradient_background_blue_white.json
    - assets/lottieFiles/gradient_background_blue_white_speedup.json
    - assets/lottieFiles/gradient_background_silver_white.json
    - assets/images/tower.png
    - assets/videos/token-tutorial.mp4
    - assets/images/campus/campus-freising.jpg
    - assets/images/campus/campus-garching.jpeg
    - assets/images/campus/campus-klinikum.jpg
    - assets/images/campus/campus-olympia.jpg
    - assets/images/campus/campus-stamm.jpeg
    - assets/images/location.png