name: campus_flutter
description: "TUM Campus App"
publish_to: 'none'
version: 5.1.6+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # networking
  dio: ^5.1.2
  drift: ^2.17.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.21
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  cached_network_image: ^3.2.3
  grpc: ^3.2.4
  protobuf: ^5.0.0
  xml: ^6.2.2
  xml2json: ^6.1.0

  # state management
  rxdart: ^0.28.0
  go_router: ^16.0.0
  flutter_riverpod: ^3.0.0
  get_it: ^9.0.5

  # user interface
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_linkify: ^6.0.0
  home_widget: ^0.8.0
  auto_size_text: ^3.0.0
  quick_actions: ^1.0.7
  flutter_native_splash: ^2.2.19
  syncfusion_flutter_core: ^31.1.19
  syncfusion_flutter_calendar: ^31.1.19
  syncfusion_flutter_charts: ^31.1.19
  syncfusion_flutter_datepicker: ^31.1.19
  google_maps_flutter: ^2.5.3
  video_player: ^2.6.1
  barcode_widget: ^2.0.4
  lottie: ^3.0.0
  timeago: ^3.4.0
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker.git
      ref: master

  # helpers
  device_info_plus: ^12.1.0
  flutter_secure_storage: ^9.2.3
  geolocator: ^14.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.0.15
  path: ^1.9.0
  url_launcher: ^6.1.10
  permission_handler: ^12.0.0+1
  uuid: ^4.2.1
  collection: ^1.18.0
  shared_preferences: ^2.1.2
  map_launcher: ^4.0.0
  html: ^0.15.4

  # firebase
  firebase_crashlytics: ^5.0.0
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0

  # localization
  easy_localization: ^3.0.6
  easy_logger: ^0.0.2
  intl: ^0.20.2
  flutter_contacts: ^1.1.9+2

dependency_overrides:
  xml2json:
    git:
      url: https://github.com/jakobkoerber/xml2json.git
      ref: master
  grpc:
    git:
      url: https://github.com/jakobkoerber/grpc-dart.git
      ref: master
  flutter_linkify:
    git:
      url: https://github.com/jakobkoerber/flutter_linkify
      ref: master

dev_dependencies:
  # code generation
  build_runner: ^2.4.9
  drift_dev: ^2.17.0

  # testing
  flutter_test:
    sdk: flutter
  test: ^1.24.3

  # linting
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/mapStyles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/logos/tum-logo-blue-text.png
    - assets/images/logos/tum-logo-rainbow.png
    - assets/images/placeholders/portrait_placeholder.png
    - assets/images/placeholders/movie_placeholder.png
    - assets/images/placeholders/news_placeholder.png
    - assets/images/placeholders/student_club_placeholder.png
    - assets/images/errors/error.svg
    - assets/lottieFiles/gradient_background_blue_red.json
    - assets/lottieFiles/gradient_background_blue_white.json
    - assets/lottieFiles/gradient_background_blue_white_speedup.json
    - assets/lottieFiles/gradient_background_silver_white.json
    - assets/images/tower.png
    - assets/videos/token-tutorial.mp4
    - assets/images/campus/campus-freising.jpg
    - assets/images/campus/campus-garching.jpeg
    - assets/images/campus/campus-klinikum.jpg
    - assets/images/campus/campus-olympia.jpg
    - assets/images/campus/campus-stamm.jpeg
    - assets/images/location.png
