name: Linting, Testing and Building

on:
  push:
    branches-ignore:
      - "dev"
      - "main"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:arch:'

      - name: Install Flutter Packages
        run: flutter pub get

      - name: Analyze Project
        run: dart analyze --fatal-warnings

      - name: Run Tests
        run: flutter test

      - name: Install latest CocoaPods Version
        run: sudo gem install cocoapods

      - name: Install CocoaPods
        run: cd ./ios && pod install

      - name: Install Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build iOS
        run: flutter build ipa --no-codesign

      - name: Build Android
        run: flutter build apk

      - name: Build Website
        run: flutter build web --base-href /
